spring:
  datasource:
    username: dbuser
    password: '{cipher}3104AQCuZIjn3AzDlL2aKYMGGJbGv4FPYcSjoopSWL5f6o88LJUYrTzTzNps7DWtRJwEbHZEsKjOqv3/JdiGZqRaJzv1exFqxHo5/DqXt7TH9OWFUTJCL4lIkTjnc/jGVPnJfU3QGA2DI+DmihDYkpN1RoaQJytOgQkqy1km8o5wykgSHIB9kOrH3es8swD1HUfJed3outKy5IEhwN5+EjChghQLGApJBiDclhIEbOcVRZH44+gR2vthZo8sXiy4eAVgIDPDKPRY7kZ4figtfTTHGrZpS8wlCe8c3Nk6mAZyL8G0Ngbnuvd6BJ0n/FeaOlETpINETUeFaE362AYzQZoQJBC8xjNGLOwtRUQwtW9sCKwc1bUC8c2B80AorwccVQpSSHw='
